### ISSUE TITLE
Codable protocol Swift 4

### ISSUE THREAD

**Issue by proactive-solutions** [ijoshsmith/json2swift#11]
Thanks a lot for the great tool. It has saved many hours for me.

Just a feature request do you have any plans to use `Codable` protocol in next version of the library.

**Comment by ijoshsmith** [comment]
Thanks. I have been thinking about how this tool will need to change once `Codable` is part of the standard library. It's definitely on my mind.

**Comment by proactive-solutions** [comment]
Thanks you are awesome (y)

**Comment by rktr09** [comment]
Hey, 
Any Plans to support Codable?

**Comment by proactive-solutions** [comment]
Hey,
Any plans to support `Codable` now?
