### ISSUE TITLE
Distribution?

### ISSUE THREAD

**Issue by BrunoMazzo** [ijoshsmith/json2swift#2]
First of all, this is a great work!!

What do you think of adding a cocoapod or/and a homebrew to help setup this Project? Maybe integrate it on Xcode build like R.swift and SwiftGen? Or create a Xcode extension?

I would like to help.

**Comment by ijoshsmith** [comment]
Hi Bruno! Thanks for the feedback. Below is an analysis of the options you presented.

---

Regarding distribution via: 

**CocoaPods**  I don't see this use case making sense. CocoaPods is good for including open source libraries in your Xcode project. I don't know why anyone would want to include `json2swift` in their application.

**homebrew** This could make it slightly easier for people to get the `json2swift` binary on their machine. But is it really worth the extra effort to distribute the tool this way? I'm not against it, but I'd need to be convinced it's worth the hassle.

---

Regarding integration via:

**Xcode build** This is not the kind of tool that needs to be frequently run, such as before every build. Your app's JSON data shouldn't be changing that often! Also, the code it generates is full of `// TODO` comments reminding a developer to rename the generated structs. It wouldn't make sense to have this kind of code created as part of a build.

**Xcode extension** I can see this being useful, if the Xcode extension API supports a use case that would enable a "Paste JSON as Swift data model" menu item. I haven't looked into Xcode extensions to know if that's possible, but I could see it being marginally easier to use than a command line tool.

---

It seems that distribution via `homebrew` and integration as an Xcode extension are viable candidates. I'm curious what other people think about this. I'll post a tweet asking for opinions.

**Comment by bre7** [comment]
+1 on brew distro

**Comment by backslash-f** [comment]
+1 on homebrew and Xcode extension.

**Comment by Lutzifer** [comment]
The way e.g. swiftgen can be integrated using cocoapods allows to lock the version and ensure, that everybody on the team has the tool available in the exact same version. This would definitely be a big plus.

Homebrew lacks this kind of locking feature (feel free to correct me on this, if you know a good way)

**Comment by burczyk** [comment]
Great tool! The easiest step is probably to put compiled binary into Releases tab in GitHub. Then we can just download it without Xcode compilation and searching for binary on our hard drive.

**Comment by ijoshsmith** [comment]
Thanks for all the input. I liked the suggestion by @burczyk the best, and published a Release with the app binary available for download. The README was updated with a link to the Releases page and an explanation of how to give the `json2swift` file execute permission. I think that should be good enough.

**Comment by mingsai** [comment]
Hi Josh,

Just want to mention that this is some great work! Although you've certainly done enough, I think the argument for support via homebrew can be made using the following:

1. Trivial package creation - 
(brew create https://github.com/ijoshsmith/json2swift/archive/v1.3.tar.gz), generates a small premade formula file (see the mini [cookbook](https://goo.gl/bRFT6G))
2. Large numbers of users manage all terminal processes using this system
3. Developer-friendly management system (easy to update)
4. Brew cask supports simple [binary-only distribution](https://goo.gl/QUERjg)
