### ISSUE TITLE
An exercise for the reader - HTTP Archive files

### ISSUE THREAD

**Issue by johndpope** [ijoshsmith/json2swift#3]
Firstly - awesome job on this project. I was thinking the other week of writing something similar. 
My use case was reading in http archive files in swift. 
(I ended up abandoning using Decodable because it was taking too long to get the data structure right and used SwiftyJSON instead. )
https://github.com/johndpope/HAR-Reader

Presumably you've used Charles proxy software on mac?
https://gist.github.com/jjarava/5f26806bba75d052c41a

It's possible to record stuff using this tool - and then save the file as a HAR file.
This format hasn't really caught on - but there's some software around that could leverage this stuff - and save everyone a bunch of time. 
https://github.com/AliSoftware/OHHTTPStubs/issues/204

This HTTP ARchive has a specification - and it's probably the most complicated json file you're ever going to see. It includes all the communications from an API - nested in yet more json. The file format is .har and there are plenty around - if you have a taste to try this - could be a nice hack.

I could use your help on this - 
https://github.com/grpc/grpc-swift/issues/2

**Comment by ijoshsmith** [comment]
Thanks for the suggestion.
