### ISSUE TITLE
Date parsing is dependent on user's calendar and time zone settings

### ISSUE THREAD

**Issue by ole** [ijoshsmith/json2swift#5]
Currently, the `DateFormatter` object that's used for date parsing doesn't have an explicit time zone and calendar set. This means it will automatically use the user's current calendar and time zone settings, i.e. the parsed `Date` values will vary depending on these settings. Is this the intended behavior? I don't think it is appropriate.

Example:

This is the model:

```json
{
    "date": "DATE_FORMAT=yyyy-MM-dd"
}   
```

And this is my code after generating the model code:

```swift
let model = RootType(json: ["date": "2016-11-08"])
print(model!.date)
```

On my machine, this prints `2016-11-07 23:00:00 +0000` because I'm in time zone +01:00. People in other time zones (or using different calendars) would get different results.

I suggest you assume that dates are in UTC and use the Gregorian calendar to avoid this. These lines should be added to the configuration of the `DateFormatter`:

```swift
// Insert after:
// let formatter = DateFormatter()
formatter.locale = Locale(identifier: "en_US_POSIX")
formatter.calendar = Calendar(identifier: .gregorian)
formatter.timeZone = TimeZone(secondsFromGMT: 0)!
// ...
// formatter.dateFormat = format
```

(I'm not 100% sure the `formatter.calendar = ` line is necessary. [Technical Q&A QA1480](https://developer.apple.com/library/content/qa/qa1480/_index.html) seems to suggest it isn't. To verify this, you'd have to change your region settings to use a different calendar and then check if setting the locale to `en_US_POSIX` automatically sets the calendar. I haven't tested this.)

Adding these lines, the code above prints `2016-11-08 00:00:00 +0000`, as I would expect.

You should check if this conflicts in any way with date formats that include an explicit time zone specifier. I haven't tested that case.

**Comment by ijoshsmith** [comment]
Thanks for the detailed feedback Ole. I had wrestled with this exact concern quite a bit, but decided that I didn't know what the best solution is. So I implemented something simple and waited for someone like you to help me think it through. Any approach I use will work for some people and be a problem for others. I think your suggestion of assuming UTC, unless a time zone is specified in the format string, makes sense for most use cases. It would not be correct for my project at work, which is probably why I ruled it out before, but that's an oddity. I'll make your suggested improvement.

Thanks,
Josh

**Comment by ijoshsmith** [comment]
@ole I have made the changes you recommended. Setting the `timeZone` property does not interfere with format-specified time zone information. The changes can be seen [here](https://github.com/ijoshsmith/json2swift/commit/84c849099e4025e44e739d86d5d2a2aca863f5d5).

**Comment by ole** [comment]
Awesome!
